#  Virtual MQTT switches maintain state
#  over Home Assistant restarts. These switches
#  mainly enable or disable automations. All
#  switches have QOS = 1, which is guaranteed delivery
#  at least once. It is important that switch state
#  changes always are delivered.

- platform: mqtt
  name: "Left Lamp Switch"
  state_topic: "switch/leftlamp/state"
  command_topic: "switch/leftlamp/state"
  qos: 1
  payload_on: "1"
  payload_off: "0"
  retain: true
