####################################################
#                                                  #
#                  Basic Settings                  #
#                                                  #
####################################################

homeassistant:
  name: My Home
  latitude: !env_var HOME_LATITUDE
  longitude: !env_var HOME_LONGITUDE
  temperature_unit: C
  time_zone: !env_var HASS_TIMEZONE
  customize: !include_dir_merge_named customizations

###  Zones  ###
zone:
- name: Home
  latitude: !env_var HOME_LATITUDE
  longitude: !env_var HOME_LONGITUDE
  radius: 20
  icon: social:people
- name: Work
  latitude: !env_var WORK_LATITUDE
  longitude: !env_var WORK_LONGITUDE
  radius: 100

###  MQTT  ###
mqtt:
  broker: localhost
  port: 1883
  client_id: home-assistant-1
  keepalive: 60
  username: !env_var MQTT_USERNAME
  password: !env_var MQTT_PASSWORD
  # certificate: /home/paulus/dev/addtrustexternalcaroot.crt
  protocol: 3.1

###  HTTP  ###
http:
  api_password: !env_var HASS_API_PASSWORD
  server_port: 8000

####################################################
#                                                  #
#                     Includes                     #
#                                                  #
####################################################

###  Devices  ###
#  Devices (usually phones) are tracked for presence detection.
device_tracker: !include device_trackers.yaml

###  Media Players  ###
#  Media players include anything (hardware or software) that
#  controls media (music, video, etc).
# media_player: !include media_players.yaml

###  Cameras  ###
camera: !include cameras.yaml

###  Lights  ###
light: !include_dir_merge_list lights

###  Switches  ###
#  Switches are anything (hardware or software) that can turn
#  on or off.
switch: !include_dir_merge_list switches

###  Sensors  ###
#  Sensors are anything (hardware or software) that has a state.
sensor: !include_dir_merge_list sensors

###  Groups  ###
group: !include groups.yaml

###  Scenes  ###
scene: !include scenes.yaml

###  Scripts  ###
script: !include_dir_named scripts

###  Automation  ###
automation: !include_dir_list automation

###  Notification  ###
# notify: !include notify.yaml

###  Weblinks  ###
weblink: !include weblink.yaml

###  Input Selects  ###
input_select: !include input_select.yaml

###  Shell Commands  ###
# shell_command: !include shell_commands.yaml

###  Logger  ###
logger: !include logger.yaml

####################################################
#                                                  #
#                     Enables                      #
#                                                  #
####################################################

###  Sun  ###
sun:

###  Logbook  ###
logbook:

###  History  ###
history:

###  Frontend  ###
frontend:
