# Multi-Room
- platform: mpd
  server: automation
  port: 6601
  location: Multi-Room Audio
# Room Audio
#- platform: mpd
#  server: bedroom
#  location: Bedroom
#- platform: mpd
#  server: craftroom
#  location: Craft Room
#- platform: mpd
#  server: automation
#  location: Living Room
# TV devices
- platform: firetv
  host: localhost:5556
- platform: snapcast
  host: automation
