alias: Bedroom Motion
trigger:
  platform: state
  entity_id: sensor.bedroom_motion
  state: 'yes'
condition:
- condition: state
  entity_id: switch.detect_motion
  state: 'on'
- condition: state
  entity_id: light.bedroom
  state: 'off'
- condition: state
  entity_id: switch.sleeping
  state: 'off'
- condition: numeric_state
  entity_id: sun.sun
  value_template: '{{ state.attributes.elevation }}'
  below: !env_var SUNSET_ELEVATION
action:
  service: homeassistant.turn_on
  entity_id: light.bedroom
