alias: Commute delay - her morning
trigger:
  platform: numeric_state
  entity_id: sensor.her_morning
  above: 45
condition:
- condition: time
  after: '07:00:00'
  before: '08:30:00'
- condition: state
  entity_id: switch.alert_delays
  state: 'on'
- condition: state
  entity_id: device_tracker.her_phone
  state: 'home'
action:
  service: notify.notify
  data_template:
    message: >
      Commute delay of {{ trigger.to_state.state|round }} minutes
