#  MQTT sensor units are located in main rooms.
#  Each reports temperature, humidity, and motion.

- platform: mqtt
  name: "Bed Room Temperature"
  state_topic: "sensor/1/temperature"
  unit_of_measurement: "C"
- platform: mqtt
  name: "Bed Room Humidity"
  state_topic: "sensor/1/humidity"
  unit_of_measurement: "%"
- platform: mqtt
  name: "Bed Room Motion"
  state_topic: "sensor/1/motion"
