#  Don't leave the lights on when no one is home!
#  But only turn them off if there are no guests present.
#  Note that `group.all_devices` is special: Its state
#  is 'home' if ANY tracked device is home, and 'not_home'
#  if EVERY tracked device is not home.

alias: Turn off lights when everyone leaves the house
trigger:
  platform: state
  entity_id: group.all_devices
  state: 'not_home'
condition:
- condition: state
  entity_id: switch.presence
  state: 'on'
- condition: state
  entity_id: switch.guests
  state: 'off'
action:
  service: light.turn_off
  entity_id: group.all_lights
