#  Send an alert if any tracked phone has a low battery.

trigger:
  platform: numeric_state
  entity_id:
  - device_tracker.his_phone
  - device_tracker.her_phone
  value_template: '{{ state.attributes.battery }}'
  below: !env_var PHONE_BATTERY_THRESHOLD
action:
  service: notify.notify
  data_template:
    message: >
      {{ trigger.to_state.attributes.friendly_name }}'s phone battery is low: {{ trigger.to_state.attributes.battery }}%
