#  Point the camera according to a preset view
#  configured on the camera.
#  There is one shell command (curl) configured
#  per preset. This automation checks the value of
#  the associated input selector and fires the
#  appropriate shell command.

alias: Camera preset control
trigger:
- platform: state
  entity_id: input_select.cam_preset
action:
  service_template: >
    {% if states.input_select.cam_preset.state == 'Kitchen' %}
      shell_command.cam_preset_kitchen
    {% elif states.input_select.cam_preset.state == 'Common Area' %}
       shell_command.cam_preset_common_area
    {% elif states.input_select.cam_preset.state == 'Entryway' %}
       shell_command.cam_preset_entryway
    {% elif states.input_select.cam_preset.state == 'Living Room' %}
       shell_command.cam_preset_living_room
    {% elif states.input_select.cam_preset.state == 'Sliding Door' %}
       shell_command.cam_preset_sliding_door
    {% elif states.input_select.cam_preset.state == 'Privacy' %}
       shell_command.cam_preset_privacy
    {% endif %}
