alias: Commute delay - her evening
trigger:
  platform: numeric_state
  entity_id: sensor.her_evening
  above: 45
condition:
- condition: time
  after: '15:30:00'
  before: '17:00:00'
  weekday:
  - mon
  - tue
  - wed
  - thu
  - fri
- condition: state
  entity_id: switch.alert_delays
  state: 'on'
- condition: state
  entity_id: device_tracker.her_phone
  state: 'not_home'
action:
  service: notify.notify
  data_template:
    message: >
      Commute delay of {{ trigger.to_state.state|round }} minutes for her
