alias: Turn on lights when someone gets home
trigger:
  platform: state
  entity_id: group.all_devices
  state: 'home'
condition:
- condition: state
  entity_id: switch.sleeping
  state: 'off'
- condition: state
  entity_id: switch.presence
  state: 'on'
action:
  service: homeassistant.turn_on
  entity_id: script.main_lights
