#  Lights that are on should turn off if
#  no motion has been detected for awhile.
#  If the motion detector state has been 'no'
#  for at least a certain number of minutes,
#  then it is safe to turn off the lights.

alias: Living Room Timer
trigger:
  platform: state
  entity_id: sensor.living_room_motion
  to: 'no'
  for:
    minutes: !env_var MOTION_TIMEOUT_MINS
condition:
- condition: state
  entity_id: switch.detect_motion
  state: 'on'
- condition: state
  entity_id: light.living_room__hall
  state: 'on'
action:
  service: homeassistant.turn_off
  entity_id: light.living_room__hall

