#  Turn on the lights when motion is detected.
#  But wait, there are some of reasons to not turn on.
#  - It is daytime
#  - Occupants are sleeping
#  - The light is already on (HA handles this, but it pollutes the log)

alias: Living Room Motion
trigger:
  platform: state
  entity_id: sensor.living_room_motion
  state: 'yes'
condition:
- condition: state
  entity_id: switch.detect_motion
  state: 'on'
- condition: state
  entity_id: light.living_room__hall
  state: 'off'
- condition: state
  entity_id: switch.sleeping
  state: 'off'
- condition: numeric_state
  entity_id: sun.sun
  value_template: '{{ state.attributes.elevation }}'
  below: !env_var SUNSET_ELEVATION
action:
  service: homeassistant.turn_on
  entity_id: light.living_room__hall
