#  When the sleep switch is turned on,
#  turn off various devices that are no
#  longer in use, especially the lights.
#  The sleep switch is automatically flipped
#  when a phone is plugged in after a certain
#  hour.

alias: Sleeping
trigger:
  platform: state
  entity_id: switch.sleeping
  state: 'on'
action:
- service: light.turn_off
  data:
    entity_id: group.all_lights
- service: switch.turn_off
  data:
    entity_id:
    - switch.smart_socket_1
    - switch.smart_socket_2
- service: media_player.turn_off
  data:
    entity_id:
    - media_player.chromecast
    - media_player.firetv
    - media_player.master_server
    - media_player.portable
