#  Alert when twitch streams go live.

alias: Streaming
trigger:
  platform: state
  entity_id:
  - sensor.twitch_fopt_membrillo
  - sensor.twitch_vooblyofficial
  - sensor.twitch_voobly_stream
  - sensor.twitch_t90official
  state: 'streaming'
  for:
    seconds: 30
condition:
- condition: state
  entity_id: device_tracker.his_phone
  state: 'home'
- condition: state
  entity_id: switch.sleeping
  state: 'no'
- condition: state
  entity_id: switch.twitch
  state: 'yes'
action:
  service: notify.notify
  data_template:
    message: >
      {{ trigger.to_state.attributes.friendly_name }} is streaming
